import * as React from "react"
import { mockApi } from "@/services/mockApi"
import type { OutreachMessage } from "@/types"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { useToast } from "@/hooks/use-toast"
import { Sparkles, Send, Mail, MessageSquare, Phone } from "lucide-react"

const MOCK_MESSAGES: OutreachMessage[] = [
  {
    id: "m_1",
    leadId: "l_1",
    type: "Email",
    content: "Hi Rahul,\n\nI noticed TechNova Solutions has been scaling rapidly. Our AI automation platform can help your team handle the increased lead volume without adding headcount. Would you be open to a quick 15-minute chat this Thursday?\n\nBest,\nAgentic Sales",
    status: "Draft",
  },
  {
    id: "m_2",
    leadId: "l_2",
    type: "WhatsApp",
    content: "Hey Priya! 👋 Saw you engaging with our CRM post. As a freelance agency owner, keeping track of clients can be tough. We've got a simple tool that does it automatically. Want to see a quick demo?",
    status: "Draft",
  },
]

export function Outreach() {
  const [messages, setMessages] = React.useState<OutreachMessage[]>(MOCK_MESSAGES)
  const [processing, setProcessing] = React.useState<string | null>(null)
  const { toast } = useToast()

  const handleSend = async (id: string, leadId: string) => {
    setProcessing(id)
    try {
      await mockApi.approveOutreach(leadId)
      setMessages(messages.map(m => m.id === id ? { ...m, status: "Sent" } : m))
      toast({ title: "Message Sent", description: "The AI agent dispatched the communication.", type: "success" })
    } catch {
      toast({ title: "Error", description: "Failed to send.", type: "destructive" })
    } finally {
      setProcessing(null)
    }
  }

  return (
    <div className="p-4 pt-6 pb-20">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold tracking-tight">Outreach Review</h1>
        <Badge variant="secondary">{messages.filter(m => m.status === 'Draft').length} Drafts</Badge>
      </div>

      <p className="text-muted-foreground mb-6">Review messages generated by your AI agents before they are sent to leads.</p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {messages.map((msg) => (
          <Card key={msg.id} className="relative overflow-hidden group">
            {msg.status === "Sent" && (
              <div className="absolute inset-0 bg-white/60 dark:bg-black/60 z-10 flex items-center justify-center backdrop-blur-[1px]">
                <Badge variant="success" className="text-sm px-4 py-1">Sent Successfully</Badge>
              </div>
            )}
            <CardHeader className="pb-3 bg-muted/40 border-b">
              <div className="flex justify-between items-start">
                <div>
                  <CardTitle className="text-base flex items-center">
                    {msg.type === "Email" && <Mail className="h-4 w-4 mr-2 text-indigo-500" />}
                    {msg.type === "WhatsApp" && <MessageSquare className="h-4 w-4 mr-2 text-green-500" />}
                    {msg.type === "Call Script" && <Phone className="h-4 w-4 mr-2 text-orange-500" />}
                    {msg.type} Draft
                  </CardTitle>
                  <CardDescription className="mt-1">Generated by Outreach Agent</CardDescription>
                </div>
                <Sparkles className="h-4 w-4 text-[--color-primary]" />
              </div>
            </CardHeader>
            <CardContent className="pt-4 pb-4">
              <div className="bg-muted/30 p-4 rounded-md text-sm whitespace-pre-wrap font-medium border border-border/50">
                {msg.content}
              </div>
              <div className="flex gap-2 mt-4">
                <Button 
                  className="w-full flex-1" 
                  disabled={processing === msg.id}
                  onClick={() => handleSend(msg.id, msg.leadId)}
                >
                  {processing === msg.id ? "Sending..." : <><Send className="h-4 w-4 mr-2" /> Approve & Send</>}
                </Button>
                <Button variant="outline" className="flex-1">Edit manually</Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  )
}
